### ISSUE TITLE
PyDFP unexpected exiting code when import

### ISSUE THREAD

**Issue by hycghana** [ansys/pydpf-core#1717] opened 2024-08-29 15:23 UTC
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

unexpected exiting code after import ansys.dpf 

print("1")
from ansys.dpf import core as dpf
print("2")    # code exited.

### Steps To Reproduce

as indicated in the code. 

It can print 1 and cannot print 2.

### Which Operating System causes the issue?

Windows

### Which DPF/Ansys version are you using?

Ansys 2021 R2

### Which Python version causes the issue?

3.12

### Installed packages

ansys-dpf-core           0.13.0
cachetools               5.5.0
certifi                  2024.7.4
charset-normalizer       3.3.2
colorama                 0.4.6
contourpy                1.3.0
cycler                   0.12.1
fonttools                4.53.1
google-api-core          2.19.2
google-api-python-client 2.142.0
google-auth              2.34.0
google-auth-httplib2     0.2.0
googleapis-common-protos 1.65.0
grpcio                   1.66.0
httplib2                 0.22.0
idna                     3.8
importlib_metadata       8.4.0
kiwisolver               1.4.5
matplotlib               3.9.2
numpy                    1.26.4
packaging                24.1
pillow                   10.4.0
pip                      22.0.4
platformdirs             4.2.2
pooch                    1.8.2
proto-plus               1.24.0
protobuf                 5.27.4
psutil                   6.0.0
pyasn1                   0.6.0
pyasn1_modules           0.4.0
pyparsing                3.1.4
python-dateutil          2.9.0.post0
pyvista                  0.44.1
requests                 2.32.3
rsa                      4.9
scipy                    1.14.1
scooby                   0.10.0
setuptools               58.1.0
six                      1.16.0
tqdm                     4.66.5
typing_extensions        4.12.2
uritemplate              4.1.1

**Comment by PProfizi** [comment] 2024-08-29 15:51
Hello @hycghana,

The issue is that `ansys-dpf-core 0.13.0` si too recent for Ansys 2021 R2.
As per this [compatibility table](https://dpf.docs.pyansys.com/version/stable/getting_started/compatibility.html#id1), the latest possible version of `ansys-dpf-core` one can use with Ansys 2021 R2 is `ansys-dpf-core==0.9.0`.

As shown in the installation documentation [here](https://dpf.docs.pyansys.com/version/stable/getting_started/install.html#install-using-pip), you can install it with:
`pip install ansys-grpc-dpf<0.4.0; pip install ansys-dpf-core<0.10.0`

**Comment by PProfizi** [comment] 2024-09-06 08:32
Closing this issue as answered. Please reopen it if you still experience the issue.

**Closed by PProfizi** 2024-09-06 08:32 UTC
Labels: good first issue
